import os

DATA_ROOT = "/net/lazer/lab-lazer/shared_projects/google_audit_reproduce/"

RAW_PARQUET_PATH = os.path.join(DATA_ROOT, "intermedidate_files","parquet_house")
RAW_PARQUET_FILE = os.path.join(RAW_PARQUET_PATH, "{date}.parquet")

OUTPUT_ROOT = os.path.join(DATA_ROOT, "intermedidate_files","handcode")
HANDCODE_PARQUET_FILE = os.path.join(OUTPUT_ROOT, "{date}.parquet")

SUMMARY_ROOT = os.path.join(DATA_ROOT, "intermedidate_files","merged_summary")
HANDCODE_PATH = os.path.join(SUMMARY_ROOT, "handcode_filtered.csv")

# Create folder if not exist
if not os.path.exists(OUTPUT_ROOT):
    os.makedirs(OUTPUT_ROOT)
if not os.path.exists(SUMMARY_ROOT):
    os.makedirs(SUMMARY_ROOT)

# Infer dates
dir_list = os.listdir(RAW_PARQUET_PATH)

DATES = []
for r in dir_list:
    if r=='.ipynb_checkpoints':
        continue
    r = r.replace('.parquet', '')
    DATES.append(r)

#DATES = ['20201006']
    
rule all:
    input:
        expand(HANDCODE_PARQUET_FILE, date=DATES)
        
rule filtering:
    input:
        RAW_PARQUET_FILE.format(date="{date}")
    output:
        HANDCODE_PARQUET_FILE
    shell:
        """
        python3 filter.py {input} {output}
        """

rule combine_summary:
    input:
        HANDCODE_PARQUET_FILE
    output:
        HANDCODE_PATH
    shell:
        """
        python3 combine.py {input} {output}
        """

      