import os

DATA_ROOT = "/net/lazer/lab-lazer/shared_projects/google_audit_reproduce/"

QRY_INFO_DIR = "../../data/qry_info_house_filter.csv"

RAW_PARQUET_PATH = os.path.join(DATA_ROOT, "raw_data")
RAW_PARQUET_FILE = os.path.join(RAW_PARQUET_PATH, "results-{date}.parquet")

OUTPUT_ROOT = os.path.join(DATA_ROOT, "intermedidate_files", "house_parquet_no_na")
UPDATE_PARQUET_FILE = os.path.join(OUTPUT_ROOT, "{date}.parquet")

# Infer dates
dir_list = os.listdir(RAW_PARQUET_PATH)

DATES = []
for r in dir_list:
    if r=='.ipynb_checkpoints':
        continue
    r = r.replace('results-', '')
    r = r.replace('.parquet', '')
    DATES.append(r)

#DATES = ['20201006']
    
rule all:
    input:
        expand(UPDATE_PARQUET_FILE, date=DATES)
        
rule drop_data:
    input: RAW_PARQUET_FILE, QRY_INFO_DIR
    output: UPDATE_PARQUET_FILE
    shell:
        """
        python3 drop_na_add_domain.py {input} {output}
        """