import os

DATA_ROOT = "/net/lazer/lab-lazer/shared_projects/google_audit_reproduce/intermedidate_files"

RAW_PARQUET_PATH = os.path.join(DATA_ROOT, "parquet_with_domain")
RAW_PARQUET_FILE = os.path.join(RAW_PARQUET_PATH, "{date}.parquet")


OUTPUT_ROOT_HOUSE = os.path.join(DATA_ROOT, "parquet_house")
UPDATE_PARQUET_FILE_HOUSE = os.path.join(OUTPUT_ROOT_HOUSE, "{date}.parquet")


# Infer dates
dir_list = os.listdir(RAW_PARQUET_PATH)

DATES = []
for r in dir_list:
    if r=='.ipynb_checkpoints':
        continue
    r = r.replace('.parquet', '')
    DATES.append(r)

#DATES = ['20201006']
    
rule all:
    input:
        expand(UPDATE_PARQUET_FILE_HOUSE, date=DATES)
        
        
rule split_office:
    input:
        RAW_PARQUET_FILE.format(date="{date}")
    output:
        UPDATE_PARQUET_FILE_HOUSE
    shell:
        """
        python3 seperate_office.py {input} {output} 
        """