import os

DATA_ROOT = "/net/lazer/lab-lazer/shared_projects/google_audit_reproduce"

RAW_PARQUET_PATH = os.path.join(DATA_ROOT, "raw_data")
RAW_PARQUET_FILE = os.path.join(RAW_PARQUET_PATH, "results-{date}.parquet")

OUTPUT_ROOT = os.path.join(DATA_ROOT, "intermedidate_files","na_summary")
UPDATE_PARQUET_FILE = os.path.join(OUTPUT_ROOT, "{date}.parquet")


SUMMARY_ROOT = os.path.join(DATA_ROOT, "intermedidate_files", "merged_summary")
SUM_PATH1 = os.path.join(SUMMARY_ROOT, "na_summary.csv")

POLI_INFO = "../../data/qry_info_house_filter.csv"

# Infer dates
dir_list = os.listdir(RAW_PARQUET_PATH)

DATES = []
for r in dir_list:
    if r=='.ipynb_checkpoints':
        continue
    r = r.replace('results-', '')
    r = r.replace('.parquet', '')
    DATES.append(r)

#DATES = ['20201006']
    
rule all:
    input:
        expand(UPDATE_PARQUET_FILE, date=DATES)
        
        
rule pre_processing:
    input:
        RAW_PARQUET_FILE, POLI_INFO
    output:
        UPDATE_PARQUET_FILE
    shell:
        """
        python3 pre_processing.py {input} {output}
        """

FILE_LIST = os.listdir(OUTPUT_ROOT)
        
rule summarize_results:
    input:
        FILE_LIST
    output:
        SUM_PATH1

    shell:
        """
        python3 combine_summaries.py {input} {output}
        """

        